//------------------------------------------------------------------------
// <generated>
//    This code was generated by WebSharper xhtml2fs version 2.4.0.0.
//
//    Changes to this file will be lost is the code is regenerated.
// </generated>
//------------------------------------------------------------------------
namespace Website.Templates

module Main =
  open System.Web.UI
  open IntelliFactory.Html
  open IntelliFactory.WebSharper
  open IntelliFactory.WebSharper.Sitelets
  
  type MainArgs<'Action> =
    {
      Footer: Context<'Action> -> list<Element<Web.Control>>
      Main: Context<'Action> -> list<Element<Web.Control>>
      Sidebar: Context<'Action> -> list<Element<Web.Control>>
      Banner: Context<'Action> -> list<Element<Web.Control>>
      Menu: Context<'Action> -> list<Element<Web.Control>>
      LoginInfo: Context<'Action> -> list<Element<Web.Control>>
    }
  
  let MainBody context (args: MainArgs<'Action>) =
    [
      Div
        [
          Tags.Comment " Login info "
          Div [Id "loginInfo"]-<
            [
            ] -< [ Text "\r\n        " ] -<
            [
            ] -< args.LoginInfo context -<
            [ Text "\r\n      " ] -<
            [
            ]
          Tags.Comment " Header "
          Div [Id "header"]-<
            [
            Div [Id "banner"]-<
              [
              ] -< [ Text "\r\n          " ] -<
              [
              ] -< args.Banner context -<
              [ Text "\r\n        " ] -<
              [
              ]
            Tags.Comment " Menu bar "
            Div [Id "menu"]-<
              [
              ] -< [ Text "\r\n          " ] -<
              [
              ] -< args.Menu context -<
              [ Text "\r\n        " ] -<
              [
              ]
            Div [Class "closer"]
            ]
          Div [Id "main-container"]-<
            [
            Tags.Comment " Main Content "
            Div [Id "main"]-<
              [
              ] -< [ Text "\r\n          " ] -<
              [
              ] -< args.Main context -<
              [ Text "\r\n        " ] -<
              [
              ]
            Tags.Comment " Sidebar "
            Div [Id "sidebar"]-<
              [
              ] -< [ Text "\r\n          " ] -<
              [
              ] -< args.Sidebar context -<
              [ Text "\r\n        " ] -<
              [
              ]
            Div [Class "closer"]
            ]
          Tags.Comment " Footer "
          Div [Id "footer"]-<
            [
            ] -< [ Text "\r\n        " ] -<
            [
            ] -< args.Footer context -<
            [ Text "\r\n      " ] -<
            [
            ]
          ]
    ]
  
  let Main title (args: MainArgs<'Action>) =
    PageContent <| fun context ->
      {
        Sitelets.Page.Default with
            Title = title
            Head = 
                [
                  Link [HRef (context.ResolveUrl("~/themes/reset.css"));Rel "stylesheet";Type "text/css"]
                  Link [HRef (context.ResolveUrl("~/themes/site.css"));Rel "stylesheet";Type "text/css"]
                ]
            Body = MainBody context args
      }
  
